---

- name: Jenkins | Create group jenkins
  group:
    name: "{{ jenkins_group }}"
    state: present
  delegate_to: "{{ item.hostname }}"
  with_items: "{{ jenkins_slaves }}"

- name: Jenkins | Create user jenkins
  user:
    name: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    createhome: yes
    home: "{{ jenkins_home_path }}"
    shell: "/bin/bash"
    generate_ssh_key: yes
  delegate_to: "{{ item.hostname }}"
  with_items: "{{ jenkins_slaves }}"

- name: Jenkins | Register ssh pub key from master
  command: cat {{ jenkins_home_path }}/.ssh/id_rsa.pub
  register: jenkins_master_key
  changed_when: false

- name: Jenkins | Authorize key from master
  authorized_key:
    user: "{{ jenkins_user }}"
    key: "{{ jenkins_master_key.stdout }}"
  delegate_to: "{{ item.hostname }}"
  with_items: "{{ jenkins_slaves }}"

- name: Jenkins | Wait for Jenkins to fully startup before continue
  uri:
    url: "{{ jenkins_url }}"
    status_code: 200,403
  retries: "{{ jenkins_check_restart_num_retries }}"
  delay: "{{ jenkins_check_restart_delay }}"
  changed_when: false
  failed_when: no

- name: Jenkins | Edit SSH config file for Jenkins user
  copy:
    mode: 0640
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
    dest: "{{ jenkins_home_path }}/.ssh/config"
    content: >
      Host *
        StrictHostKeyChecking no

- name: Jenkins | Registering create ssh users
  jenkins_script:
    script: "{{ lookup('file', 'security/Credentials.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
    args:
      id: "{{ item.id }}"
      username: "{{ item.username | default('') }}"
      password: "{{ item.password | default('') }}"
      description: "{{ item.description }}"
      cred: "{{ item.cred | default('') }}"
      text: "{{ item.text | default('') }}"
  with_items: "{{ jenkins_credentials }}"

- name: Jenkins | Registering slaves in Jenkins master instance
  jenkins_script:
    script: "{{ lookup('file', 'slaves/RegisterSlave.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
    args:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      home: "{{ item.home }}"
      executors: "{{ item.executors }}"
      label: "{{ item.label }}"
      hostname: "{{ item.hostname }}"
      credentials: "{{ item.credentials }}"
  with_items:
    - "{{ jenkins_slaves }}"

- name: Jenkins | Known hosts slaves
  known_hosts:
    path: "{{ jenkins_home_path }}/.ssh/known_hosts"
    name: "{{ item.hostname }}"
    key: "{{ lookup('pipe', 'ssh-keyscan -t rsa ' + item.hostname ) }}"
    state: present
  with_items:
    - "{{ jenkins_slaves }}"

- name: Jenkins | Update known_hosts Permissions
  file:
    path: "{{ jenkins_home_path }}/.ssh/known_hosts"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_group }}"
  when:
    - jenkins_slaves is defined
    - jenkins_slaves | length > 0

- name: Jenkins | Configure slave master access
  jenkins_script:
    script: "{{ lookup('file', 'slaves/SlaveMasterAccess.groovy') }}"
    user: "{{ jenkins_admin_username }}"
    password: "{{ jenkins_admin_password }}"
    url: "{{ jenkins_url }}"
